#!/usr/bin/env python3
"""Validate commit messages for release-please compatibility.

Core rule: the subject line must follow conventional-commit format,
``<type><optional-scope>!?: <description>``. release-please keys versioning
and changelog sections off it, so a malformed subject silently produces no
version bump -- the change just quietly never ships.

Two modes, so a local hook and CI enforce exactly the same thing:

* ``check-commit-message.py <msgfile>...`` -- pre-commit ``commit-msg`` stage.
* ``check-commit-message.py --range <base>..<head>`` -- CI, over a push or PR
  range. Merge commits are skipped; their subjects are generated by the forge
  and are not ours to format.

``--types fix,feat,...`` overrides the allowed type list for repos with extra
vocabulary. Keep any per-repo list in the consuming repo's OWN config
(pre-commit ``args:`` / action ``types:`` input), never by editing this file.

Mode-specific behaviour, each deliberate:

* FILE MODE ONLY -- a merge in progress (``.git/MERGE_HEAD`` exists) skips
  validation entirely. git fires commit-msg for every local merge, clean or
  conflicted, so validating there blocks an ordinary ``git merge --no-ff`` and
  strands the working tree mid-merge.
* FILE MODE ONLY -- ``fixup!``/``squash!``/``amend!`` subjects pass: they are
  autosquash artifacts meant to be folded away by ``git rebase --autosquash``.
  RANGE MODE still rejects them -- one reaching a validated range means the
  squash was forgotten, which is worth failing.
* ``Revert "..."`` (the forge's Revert button) fails with a targeted message.
  release-please cannot parse that subject either, so the commit would vanish
  silently from the changelog; the convention is a manual
  ``revert(scope): description``.
* A body line that *looks* like a breaking-change footer but is not the exact
  token (``BREAKING CHANGE: `` / ``BREAKING-CHANGE: ``, case-sensitive) fails.
  ``Breaking change:`` ships a breaking change as a silent minor/patch bump --
  a worse outcome than the one this script exists to prevent.

## A rule that was removed, and why

An earlier version also rejected any ``(`` in a body line, on the theory that
release-please's parser silently skipped such commits. That was measured
against a real repository's history and did not reproduce: of 60 commits
examined, 44 had parentheses in the body and none were dropped from the
changelog. The rule was rejecting roughly three-quarters of normal commit
bodies to prevent a failure that no longer happens, so it is gone.

If a commit ever DOES go missing from a release PR, re-test that first -- with
a reproduction, not from memory.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

DEFAULT_TYPES = (
    "fix",
    "feat",
    "chore",
    "docs",
    "refactor",
    "perf",
    "test",
    "ci",
    "build",
    "revert",
    "style",
)

AUTOSQUASH_RE = re.compile(r"^(fixup|squash|amend)! ")
REVERT_BUTTON_RE = re.compile(r'^Revert "')
BREAKING_LOOSE_RE = re.compile(r"^\s*breaking[ -]changes?\s*:", re.IGNORECASE)
BREAKING_EXACT_RE = re.compile(r"^(BREAKING CHANGE|BREAKING-CHANGE): ")


def subject_pattern(types: tuple[str, ...]) -> re.Pattern[str]:
    """Build the subject regex for an allowed-type list."""
    return re.compile(rf"^({'|'.join(re.escape(t) for t in types)})" r"(\([^)]+\))?!?: .+")


def check_message(
    text: str,
    label: str,
    types: tuple[str, ...] = DEFAULT_TYPES,
    *,
    autosquash_ok: bool = False,
) -> int:
    """Validate one commit message. Returns 0 on success, 1 on violation."""
    body_lines = [line for line in text.splitlines() if not line.lstrip().startswith("#")]
    if not body_lines or not body_lines[0].strip():
        sys.stderr.write(f"{label}: commit message is empty\n")
        return 1

    subject = body_lines[0]
    failed = 0

    if autosquash_ok and AUTOSQUASH_RE.match(subject):
        sys.stderr.write(f"{label}: autosquash subject accepted (fold it away with git rebase --autosquash)\n")
    elif REVERT_BUTTON_RE.match(subject):
        sys.stderr.write(
            f"{label}: this looks like the forge's Revert button subject\n"
            f"  got: {subject!r}\n"
            "  release-please cannot parse it, so the commit would vanish\n"
            "  silently from the changelog. Amend it to the convention:\n"
            "    revert(<scope>): <what is being reverted>\n"
            "  (git commit --amend, or retitle before merging)\n"
        )
        failed = 1
    elif not subject_pattern(types).match(subject):
        sys.stderr.write(
            f"{label}: commit subject does not match conventional-commit format\n"
            f"  got: {subject!r}\n"
            "  expected: <type><optional-scope>!?: <description>\n"
            f"  valid types: {', '.join(types)}\n"
        )
        failed = 1

    for line in body_lines[1:]:
        if BREAKING_LOOSE_RE.match(line) and not BREAKING_EXACT_RE.match(line):
            sys.stderr.write(
                f"{label}: malformed breaking-change footer\n"
                f"  got: {line.strip()!r}\n"
                '  release-please only recognises the exact tokens "BREAKING CHANGE: "\n'
                '  or "BREAKING-CHANGE: " (case-sensitive, singular). As written this\n'
                "  ships a breaking change as a silent minor/patch bump.\n"
            )
            failed = 1

    return failed


def merge_in_progress() -> bool:
    """True when the working repo is mid-merge (git fires commit-msg then too)."""
    try:
        proc = subprocess.run(
            ["git", "rev-parse", "--git-path", "MERGE_HEAD"],
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return False
    return Path(proc.stdout.strip()).exists()


RANGE_SIDE_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._/~^-]*$")


def validate_range(rev_range: str) -> bool:
    """Accept only a plain two-dot range of SHA-or-ref shapes (no leading '-')."""
    sides = rev_range.split("..")
    return len(sides) == 2 and all(RANGE_SIDE_RE.match(side) for side in sides)


def _messages_in_range(rev_range: str) -> list[tuple[str, str]] | None:
    """[(sha, message)] for non-merge commits in ``rev_range``; None if unresolvable."""
    try:
        shas = subprocess.run(
            ["git", "log", "--format=%H", "--no-merges", rev_range],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split()
    except subprocess.CalledProcessError as exc:
        sys.stderr.write(
            f"cannot resolve range {rev_range!r}: {exc.stderr.strip()}\n"
            "  (a force-push rewrites history so the old tip no longer exists;\n"
            "  re-run against a range that exists, or validate the new tip alone)\n"
        )
        return None
    return [
        (
            sha,
            subprocess.run(
                ["git", "log", "-1", "--format=%B", sha],
                capture_output=True,
                text=True,
                check=True,
            ).stdout,
        )
        for sha in shas
    ]


def main(argv: list[str]) -> int:
    """Entry point; returns process exit code."""
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("msgfiles", nargs="*", help="commit-msg files (pre-commit hook mode)")
    parser.add_argument("--range", dest="rev_range", help="<base>..<head> (CI mode)")
    parser.add_argument(
        "--types",
        default=",".join(DEFAULT_TYPES),
        help="comma-separated allowed types (per-repo override; default canonical list)",
    )
    args = parser.parse_args(argv[1:])

    types = tuple(t.strip() for t in args.types.split(",") if t.strip())
    if not types:
        sys.stderr.write("--types resolved to an empty list\n")
        return 1

    if args.rev_range:
        if not validate_range(args.rev_range):
            sys.stderr.write(f"malformed range {args.rev_range!r}: expected <base>..<head>\n")
            return 1
        resolved = _messages_in_range(args.rev_range)
        if resolved is None:
            return 1
        targets = [(sha[:8], text) for sha, text in resolved]
        autosquash_ok = False
    elif args.msgfiles:
        if merge_in_progress():
            sys.stderr.write("merge in progress: skipping commit-message check (subject is git-generated)\n")
            return 0
        targets = [(path, Path(path).read_text(encoding="utf-8")) for path in args.msgfiles]
        autosquash_ok = True
    else:
        parser.print_usage(sys.stderr)
        return 1

    failed = 0
    for label, text in targets:
        failed |= check_message(text, label, types, autosquash_ok=autosquash_ok)

    if targets and not failed:
        sys.stderr.write(f"checked {len(targets)} commit message(s): ok\n")
    return failed


if __name__ == "__main__":
    sys.exit(main(sys.argv))
